Numpy + Pandas intro

In [1]:
import numpy as np


In [ ]:
# --- numpy--- pythonda raqamlar bn ishliydigan kutubxona
# --- C tilida yozilgan(c qoidalari buyicha), pythondan 100 barobar tez ishlaydi

In [6]:
ls = [1,2,3,4]
arr = np.array(ls)   

print(ls)
print(arr)

[1, 2, 3, 4]
[1 2 3 4]


In [3]:
# ls xar bir elementini 4 darajaga kutarish

for i in ls:
    print(i**4)

1
16
81
256


In [5]:
arr**4

array([  1,  16,  81, 256])

In [7]:
a = arr**4
print(a)

[  1  16  81 256]


In [ ]:
arr.ndim  #  ndim o'lchamlar soni(number of demension)

In [8]:
ls2 = [[1,2,3],[4,5,6]]
arr2 = np.array(ls2)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr2.ndim   # arr2 2 ulchamligini chiqardi

2

In [68]:
ls2 = [[[1,2,3],[4,5,6]],[[7,8,9],[6,7,99]]]
arr3 = np.array(ls2)
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 6  7 99]]]


In [18]:
arr3.ndim

3

In [ ]:
arr3.nbytes   #elementning xotirada egallagan joyi

96

In [30]:
arr3.size   #elementlar sonini kursatadi

12

In [ ]:
arr3.dtype  # elementning tipi 

dtype('int64')

In [ ]:
arr = arr3.astype('int8') # 1 ta element uchun 8 bit joy ajrat degani

In [29]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [6, 7, 3]]], dtype=int8)

In [31]:
arr + 100

array([[[101, 102, 103],
        [104, 105, 106]],

       [[107, 108, 109],
        [106, 107, 103]]], dtype=int8)

In [33]:
arr4 = np.arange(1,100,1)   #1 dan 100 gacha 1 qadammda
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr4 = np.arange(1,100,1)   #1 dan 100 gacha 50 dan kattasi
filter1 = arr4 > 50
arr4[filter1]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [36]:
arr4 = np.arange(1,100,1)   #1 dan 100 gacha 50 dan kattasi
arr4[arr4 > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr4 = np.arange(1,100)   # juft sonlar topish
arr4[arr4%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [41]:
arr4 = np.arange(1,100)     # toq sonlar topish
arr4[arr4%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [48]:
arr4 = np.arange(1,100)     # 37 dan katta 76 dan kichik sonlar
filter1 = arr4 > 37
filter2 = arr4 < 76
filter3 = filter1 & filter2
arr4[filter3]

array([38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75])

In [52]:
arr4 = np.arange(1,100)     # 37 dan katta 76 dan kichik sonlar
filter4 = (arr4>37)&(arr4<76)
arr4[filter4]

array([38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75])

In [53]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([4,5,6,7])
arr1+arr2

array([ 5,  7,  9, 11])

In [69]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 6,  7, 99]]])

In [70]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr3[0][0]

array([1, 2, 3])

In [72]:
arr3[0][0][0]

np.int64(1)

In [74]:
arr3[0,0,0]

np.int64(1)

In [75]:
arr3[1,1,2]

np.int64(99)

In [76]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 6,  7, 99]]])

In [78]:
arr3[1:2,0:2]

array([[[ 7,  8,  9],
        [ 6,  7, 99]]])

In [79]:
arr3[1,0:2,1:]

array([[ 8,  9],
       [ 7, 99]])

In [82]:
ls2 = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
arr6 = np.array(ls2)
print(arr6)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [87]:
arr6[0,0,1:]

array([2, 3])

In [90]:
arr6[0,0:2,1:]

array([[2, 3],
       [5, 6]])

In [92]:
arr6[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
arr6[0][:][1]

array([4, 5, 6])

In [98]:
arr6[0,0:2,1:3]

array([[2, 3],
       [5, 6]])

In [101]:
arr6[0:2,0,1:]

array([[2, 3],
       [8, 9]])